### ISSUE TITLE
Strange behavior of links

### ISSUE THREAD

**Issue by aadimator** [mathieudutour/foam-gatsby-template#12]
At first, I tried this template with some modifications but it showed some strange behavior, so I decided to use the template as it is, without any modifications (just changing the `pathPrefixvalue` to repo name) to see if the problem persists. It's working perfectly fine here: https://mathieudutour.github.io/foam-gatsby-template/, but when I try to run the same code here https://aadimator.github.io/foam-notes/, it behaves differently.

The problem is, that once I hover over the backlinks, it doesn't show the popover (`Tippy.js`) and the other thing being that if I click on a backlink inside the main content, it **opens up a new page** instead of using StackedPage, but when I click on the link from the **Referred in** section, it displays that page using StackedPages just fine. I've attached a video showcasing the above-mentioned peculiarities. 

https://www.loom.com/share/698cab5d27f344108940409798135f12

Here's the link to my repo: https://github.com/aadimator/foam-notes
As you can see, it's almost exactly the same as that in the original template repo. 
Can you please help me figure out the problem? Thanks

**Comment by mathieudutour** [comment]
That's the issue: https://github.com/gatsbyjs/gatsby/issues/26541. Not sure how to fix yet

**Comment by mathieudutour** [comment]
Should be fixed in the new version of the theme
