### ISSUE TITLE
Github actions fails at  Build website step

### ISSUE THREAD

**Issue by hungsu** [mathieudutour/foam-gatsby-template#14]
![image](https://user-images.githubusercontent.com/1990680/93669378-9efa1400-fa48-11ea-8627-54e7462d6c39.png)

**Comment by hungsu** [comment]
This issue began quite recently. I noticed it when I committed a new change yesterday, but this problem seems to have nothing to do with my commit. 

Running the action on older commits where it worked previously, will now fail. So it seems perhaps the previous npm install step may be causing this to fail.

Oddly, when I run `npm run install` and `npm run build -- --prefix-paths` in my local Ubuntu 18.04 env it completes without issue

**Comment by hungsu** [comment]
Hi Mathieu, not sure if you're using Foam and this repo anymore.

Resolved this on my end by including a working package-lock.json.

**Comment by mathieudutour** [comment]
I fixed a couple of bugs yesterday which might have been related to that - but I couldn't repro so not sure
