### ISSUE TITLE
[Question] Is it possible to support folders?

### ISSUE THREAD

**Issue by hikerpig** [mathieudutour/foam-gatsby-template#17]
# Is it possible to support folders?

### File Structure

Say I have these example files in a Foam project with foam generated link texts.

```
index.md
fruit
├── apple.md
├── orange.md
```

`apple.md`:

```markdown
Apple
===

I will link [[orange]] here.

[//begin]: # "Autogenerated link references for markdown compatibility"
[orange]: orange "Orange"
[//end]: # "Autogenerated link references"
```

`orange.md`:

```markdown
Orange
===

An orange is an orange is an orange.
```

### Current problem

When clicking the orange link in the apple page ( mysite.com/fruit/apple ), the link will lead to ( mysite.com/orange ) - which will be 404.

Is there any chance that I can configure the gatsby-theme-garden to make it link to ( mysite.com/fruit/orange ) ? Though I do know that it is somehow contradictory with Roam's convention.

**Comment by mathieudutour** [comment]
Tracked in https://github.com/mathieudutour/gatsby-digital-garden/issues/49
