### ISSUE TITLE
gatsby build throws "Reducers may not dispatch actions"

### ISSUE THREAD

**Issue by synesthesia** [mathieudutour/foam-gatsby-template#2]
Hi Mathieu

I love the idea, but fell at first hurdle...

```
error "gatsby-theme-garden" threw an error while running the createPages lifecycle:
Reducers may not dispatch actions.
```
After first getting this I edited `_layouts/gatsby-config.js`  to set the pathPrefix to the subdirectory my GH Pages appears at but still same error. Any clues please?

```
module.exports = {
  pathPrefix: `/garden`,
  siteMetadata: {
    title: `Garden`,
  },
  plugins: [
    {
      resolve: `gatsby-theme-garden`,
      options: {
        rootNote: "readme",
        contentPath: `${__dirname}/..`,
        ignore: [
          "**/_layouts/**",
          "**/.git/**",
          "**/.github/**",
          "**/.vscode/**",
        ],
      },
    },
  ],
};
```

Further tests:
*  did a straight fork of you repo and the build fails in the same way.
* then tried fixing the Gatsby version at the exact base version in package.json but still no change

**Comment by mathieudutour** [comment]
it's an issue with Gatsby: https://github.com/gatsbyjs/gatsby/issues/25478. Should be fixed soon

**Comment by synesthesia** [comment]
I see the team have released an update so will will try with new version of Gatsby
