### ISSUE TITLE
Broken GraphQL Query when running Action

### ISSUE THREAD

**Issue by ghost** [mathieudutour/foam-gatsby-template#7]
When the Action runs, and it gets to the `build website` portion of the workflow, I get this error:

`Cannot query field "gardenConfig" on type "Query".`

I _think_ I have the config set up right, but just in case, here is the repo:

https://github.com/twhite96/dev-research-gatsby

`gatsby-config.js`:

```js

module.exports = {
  pathPrefix: `/dev-research`,
  siteMetadata: {
    title: `Dev Research`,
  },
  plugins: [
    {
      resolve: `gatsby-theme-garden`,
      options: {
        rootNote: "/readme",
        contentPath: `${__dirname}/..`,
        ignore: [
          "**/_layouts/**",
          "**/.git/**",
          "**/.github/**",
          "**/.vscode/**",
        ],
      },
    },
  ],
};
```

**Comment by yenly** [comment]
I encountered this same issue. Update your pathPrefix to name of your repo.

**Comment by ghost** [comment]
> I encountered this same issue. Update your pathPrefix to name of your repo. 

Without the slash in front?

**Comment by ghost** [comment]
I changed the pathPrefix, now I get this error: `We've encountered an error: Objects are not valid as a React child (found: Error: ENOENT: no such file or directory, open '[directory name]/dev-research-gatsby/.cache/match-paths.json'). If you meant to render a collection of children, use an array instead.`

**Comment by yenly** [comment]
Was the error from keeping the slash, like this?
```
pathPrefix: `/dev-research-gatsby`,
```

**Comment by ghost** [comment]
> Was the error from keeping the slash, like this?
> 
> ```
> pathPrefix: `/dev-research-gatsby`,
> ```

Nope. With the slash I get the GraphQL error. Without it, I get the missing .json file.

There's mo `.cache` folder either when I run the build command. I have Gatsby installed. Not sure what is happening.

**Comment by hungsu** [comment]
Hello! I had exactly the same errors and I THINK i might have a solution, but would love Mathieu Du Tour to weigh in.

So you should completely ignore the commands in package.json. I found my clues in .github/workflows/deploy-foam.yml

1. In gatsby-config.js, set pathPrefix to `''` (an empty string)
2. from _layout, run `npm install` then `npm run build -- --prefix-paths`
3. You now have a generated working static site in `_layout/public`!

**Comment by mathieudutour** [comment]
So the `pathPrefix` is for when your website is deployed in the nested path (for example this repo is deployed to https://mathieudutour.github.io/foam-gatsby-template, not just https://mathieudutour.github.io). It needs to match where it's deployed. See https://www.gatsbyjs.org/docs/path-prefix/

I'm not sure why the error can happen tho. I published a new version of the theme, bumping the version of gatsby-theme-garden in the _layout/package.json to 0.1.44 might fix it?

**Comment by hungsu** [comment]
Thanks Mathieu! Seems in general that keeping the pathPrefix empty fixes it for our case, with no need to update the gatsby-theme-garden version.

**Comment by ghost** [comment]
I'll try this later today. Thanks @hungsu and @mathieudutour

**Comment by ghost** [comment]
> Hello! I had exactly the same errors and I THINK i might have a solution, but would love Mathieu Du Tour to weigh in.
> 
> So you should completely ignore the commands in package.json. I found my clues in .github/workflows/deploy-foam.yml
> 
> 1. In gatsby-config.js, set pathPrefix to `''` (an empty string)
> 2. from _layout, run `npm install` then `npm run build -- --prefix-paths`
> 3. You now have a generated working static site in `_layout/public`!

This worked for me. I am going to keep this issue up in case someone else runs into this issue, unless you want to close it @mathieudutour
